[package]
name = "check_balance"
version = "0.1.0"
edition = "2024"

[dependencies]
# wepay = { git = "https://github.com/mantvmass/wepay.git" } 
wepay = { path = "../../"} 
tokio = { version = "1", features = ["full"] }
dotenvy = "0.15"