name: Rust CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Checkout code
    - uses: actions/checkout@v4

    # ติดตั้ง Rust toolchain
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        components: rustfmt, clippy

    # Cache dependencies
    - name: Cache cargo
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    # ตรวจสอบ format code
    - name: Check formatting
      run: cargo fmt --all -- --check

    # เรียกใช้ Clippy สำหรับ linting
    - name: Run Clippy
      run: cargo clippy --all-targets --all-features -- -D warnings

    # รัน tests
    - name: Run tests
      run: cargo test --all-features --verbose